[workspace]
members = [
    "perovskite_server",
    "perovskite_client",
    "perovskite_core",
    "perovskite_game_api"
]
resolver = "2"

[profile.release]
debug = 1
# lto = "thin"
incremental = true

[profile.maxopt]
debug = 1
opt-level = 3
lto = "thin"
inherits = "release"
