name: Experimnental Rust Mac Build ARM

on:
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Stamp
        run: |
          echo "GH_BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "GH_RUN_ID=macos-14-${{ github.run_number }}" >> $GITHUB_ENV
          echo "GH_COMMIT=${{ github.sha }}" >> $GITHUB_ENV
          echo "GH_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Build
        run: |
          cmake_commit="b4e46db74e74a8c1650b38b1da222284ce1ec5ce"
          tap_name="local/pinned"
          echo "Creating local tap (no git)..."
          brew uninstall cmake
          brew tap-new --no-git "$tap_name" >/dev/null
          cmake_formula_dir="$(brew --repo "$tap_name")/Formula"
          mkdir -p "$cmake_formula_dir"
          cmake_rb_link="https://raw.githubusercontent.com/Homebrew/homebrew-core/$cmake_commit/Formula/c/cmake.rb"
          cmake_rb_path="$cmake_formula_dir/cmake.rb"
          echo "Downloading cmake.rb from $cmake_rb_link"
          curl -fsSL "$cmake_rb_link" -o "$cmake_rb_path"
          echo "Installing cmake 3.31.6 from custom tap..."
          brew install "$tap_name/cmake"
          echo "cmake downgraded"
          brew install protobuf
          rustup target add aarch64-apple-darwin
          rustup update
          cargo build --target aarch64-apple-darwin --profile=maxopt --bin perovskite_client --features static-mvk
          mv target/aarch64-apple-darwin/maxopt/perovskite_client target/aarch64-apple-darwin/maxopt/perovskite_client_mac_arm64
      - name: Upload the artifacts
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "target/aarch64-apple-darwin/maxopt/perovskite_client_mac_arm64"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
