name: Rust Windows Build

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Stamp
      run: |
        echo "GH_BUILD_DATE=$(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ' -AsUTC)" >> $env:GITHUB_ENV
        echo "GH_RUN_ID=windows-${{ github.run_number }}" >> $env:GITHUB_ENV
        echo "GH_COMMIT=${{ github.sha }}" >> $env:GITHUB_ENV
        echo "GH_BRANCH=$($env:GITHUB_REF -replace 'refs/heads/','')" >> $env:GITHUB_ENV

    - name: Build
      run: |
        choco install protoc
        choco install ninja
        rustup update
        cargo build --profile maxopt --bin perovskite_client
    - name: Upload the artifacts
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "target/maxopt/perovskite_client.exe"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
