name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v3
    - name: Build
      run: |
        sudo apt-get install protobuf-compiler libasound-dev libdbus-1-dev pkg-config
        rustup install 1.88
        cargo +1.88 build --verbose --release
      # Unfortunately we need --release for loom tests to finish in a reasonable time
    - name: Test core
      run: cargo +1.88 test --verbose -p perovskite_core --release
    - name: Test game content
      run: cargo +1.88 test --verbose -p perovskite_game_api --release
    - name: Test server
      run: cargo +1.88 test --verbose -p perovskite_server --release
    - name: Test client
      run: cargo +1.88 test --verbose -p perovskite_client --release
